name: PR Title JIRA Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - edited
      - synchronize
  merge_group:
    types: [checks_requested]
  push:
    branches:
      # A branch prefix used by graphite's merge queue
      # https://graphite.dev/docs/merge-queue-optimizations#end-user-experience-when-using-parallel-ci
      - 'gtmq_**'

jobs:
  validate-pr-title:
    name: PR Title JIRA Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        env:
          PR_TITLE_ENV: ${{ github.event.pull_request.title }}
        run: |
          title_regex='[A-Z]{1,}-[0-9]+'
          PR_TITLE_VAR="$PR_TITLE_ENV"

          if [[ -z "$PR_TITLE_VAR" ]]; then
            echo "Error: PR title is empty. Cannot validate JIRA ticket."
            exit 1
          fi

          if [[ "$PR_TITLE_VAR" =~ $title_regex ]]; then
            echo "PR title contains a JIRA ticket number."
          else
            echo "PR title does not contain a JIRA ticket number in the expected format (e.g., JIRAPROJECT-DIGITS)."
            echo "The title was: '$PR_TITLE_VAR'"
            exit 1
          fi
